speedrun_option_load()

menu_init("------ SPEEDRUN ------")

menu_add_line("HARD MODE",0,"speedrun_hardmode")
menu_add_line("STABLE SEED",0,"speedrun_stableseed")
menu_add_line("SKIP CUTSCENES",0,"speedrun_skipcuts")
//menu_add_line("ACTION ONLY",0,"speedrun_actiononly")
//menu_add_line("SKIP REPLAY",0,"speedrun_skipreplay")
//menu_add_line("DRAGON DASH MAX",0,"speedrun_dragdashmax")
//menu_add_line("SECRET BOSS",0,"speedrun_secrtboss")
menu_add_line("SHOW TIMER",0,"speedrun_showtimer")
menu_add_line("SHOW DEATH COUNT",0,"speedrun_showdeath")
menu_add_line("NO SLOWMO",0,"speedrun_noslowmo")
menu_add_line("SLOWMO MODE",3,"speedrun_chronos_mode",["Normal","Super Hot","Edgerunner"])
menu_add_line("ONE LIFE",0,"speedrun_nodeathmode")
menu_add_line("GAME SPEED",3,"speedrun_gamespeedid",["x1.0","x1.25","x1.5","x2"])
menu_add_line("CHARACTER",3,"speedrun_char_mode",["Normal","Zero","Gun Zero","Infinty","Fifteen","Murasama","Gun Zero + Infinty","Gun Zero + Fifteen","Gun Zero + Murasama"])
menu_add_line("RULE",3,"speedrun_rule",["Any%","Break The Lights","True Pascifist"])
//menu_add_line("WEAPON",0,"speedrun_weapon")
menu_add_line("STARTING LEVEL",3,"speedrun_startlevelid",["Mission PART.1","Mission PART.2","BOSS"])
//menu_add_line("SHOW HIGHTSCORE",0,"speedrun_hardmode")
menu_add_line("BEGIN RUN",1,function(){
		event_user(1)
	})
menu_add_line("CANCEL",1,function(){with obj_title_screen {start=false start_timer = 0} instance_destroy()})