//gpu_set_blendmode(bm_add)
//draw_set_alpha(.3)
//blur_set(surface_get_texture(application_surface),8)
//draw_surface(application_surface,0,0)
//blur_reset()
////draw_set_color(c_purple)
////draw_rectangle(-1,-1,CAMERA_X_SIZE,CAMERA_Y_SIZE,0)
//draw_set_alpha(1)
//gpu_set_blendmode(bm_normal)

